@extends('layouts.app')
@section('title','Reports')
@section('page-title','Reports')

@section('content')
<div class="row g-3">
    {{-- Generate Report Card --}}
    <div class="col-lg-4">
        <div class="form-card h-100">
            <h6 class="fw-700 mb-3"><i class="fa-solid fa-chart-bar me-2 text-primary"></i>Generate Report</h6>
            <form action="{{ route('admin.reports.generate') }}" method="POST">
                @csrf
                <div class="mb-3">
                    <label class="form-label fw-600 small">Report Title *</label>
                    <input type="text" name="title" class="form-control" placeholder="e.g. April Users Report" required>
                </div>
                <div class="mb-4">
                    <label class="form-label fw-600 small">Report Type *</label>
                    <select name="type" class="form-select" required>
                        <option value="">Select type…</option>
                        <option value="summary">Summary (All Data)</option>
                        <option value="users">Users Report</option>
                        <option value="sessions">Sessions Report</option>
                        <option value="enrollments">Enrollments Report</option>
                        <option value="materials">Materials Report</option>
                    </select>
                </div>
                <button type="submit" class="btn btn-primary text-white w-100">
                    <i class="fa-solid fa-file-chart-column me-2"></i>Generate
                </button>
            </form>
        </div>
    </div>

    {{-- Reports List --}}
    <div class="col-lg-8">
        <div class="table-card">
            <div class="table-header"><strong>Generated Reports</strong></div>
            <div class="table-responsive">
                <table class="table table-hover align-middle mb-0">
                    <thead><tr><th>Title</th><th>Type</th><th>Generated By</th><th>Date</th><th>Actions</th></tr></thead>
                    <tbody>
                    @forelse($reports as $r)
                        <tr>
                            <td class="fw-500">{{ $r->title }}</td>
                            <td><span class="badge badge-info">{{ ucfirst($r->type) }}</span></td>
                            <td class="small">{{ $r->generator->name ?? '—' }}</td>
                            <td class="small text-muted">{{ $r->created_at->format('d M Y H:i') }}</td>
                            <td>
                                <div class="d-flex gap-1">
                                    <a href="{{ route('admin.reports.show',$r) }}" class="btn btn-sm btn-outline-info" title="View">
                                        <i class="fa-solid fa-eye"></i>
                                    </a>
                                    <form action="{{ route('admin.reports.destroy',$r) }}" method="POST"
                                        onsubmit="return confirm('Delete this report?')">
                                        @csrf @method('DELETE')
                                        <button class="btn btn-sm btn-outline-danger" title="Delete">
                                            <i class="fa-solid fa-trash"></i>
                                        </button>
                                    </form>
                                </div>
                            </td>
                        </tr>
                    @empty
                        <tr><td colspan="5" class="text-center text-muted py-5">No reports generated yet.</td></tr>
                    @endforelse
                    </tbody>
                </table>
            </div>
            @if($reports->hasPages())
                <div class="p-3">{{ $reports->links() }}</div>
            @endif
        </div>
    </div>
</div>
@endsection
