@extends('layouts.app')
@section('title', $report->title)
@section('page-title', 'Report: ' . $report->title)

@section('content')
<div class="form-card">
    <div class="d-flex justify-content-between align-items-center mb-4 flex-wrap gap-2">
        <div>
            <h5 class="fw-700 mb-1">{{ $report->title }}</h5>
            <span class="badge badge-info me-2">{{ ucfirst($report->type) }}</span>
            <span class="text-muted small">Generated by {{ $report->generator->name ?? '—' }} on {{ $report->created_at->format('d M Y H:i') }}</span>
        </div>
        <div class="d-flex gap-2">
            <button onclick="window.print()" class="btn btn-sm btn-outline-secondary">
                <i class="fa-solid fa-print me-1"></i>Print
            </button>
            <form action="{{ route('admin.reports.destroy',$report) }}" method="POST"
                onsubmit="return confirm('Delete this report permanently?')">
                @csrf @method('DELETE')
                <button class="btn btn-sm btn-outline-danger"><i class="fa-solid fa-trash me-1"></i>Delete</button>
            </form>
            <a href="{{ route('admin.reports.index') }}" class="btn btn-sm btn-outline-secondary">Back</a>
        </div>
    </div>

    @if($report->type === 'summary')
        <div class="row g-3 mb-4">
            @foreach([
                ['Total Users',     $data['total_users'],     '#dbeafe','#2563eb','fa-users'],
                ['Trainers',        $data['total_trainers'],  '#dcfce7','#16a34a','fa-chalkboard-user'],
                ['Trainees',        $data['total_trainees'],  '#fef9c3','#ca8a04','fa-user-graduate'],
                ['Total Sessions',  $data['total_sessions'],  '#f3e8ff','#9333ea','fa-calendar-days'],
                ['Active Sessions', $data['active_sessions'], '#dcfce7','#16a34a','fa-circle-play'],
                ['Enrollments',     $data['total_enrolls'],   '#ffedd5','#ea580c','fa-clipboard-list'],
                ['Materials',       $data['total_materials'], '#e0f2fe','#0284c7','fa-file-arrow-up'],
            ] as [$lbl,$val,$bg,$ic,$icon])
            <div class="col-6 col-md-3">
                <div class="stat-card text-center">
                    <div class="icon mx-auto" style="background:{{ $bg }}">
                        <i class="fa-solid {{ $icon }}" style="color:{{ $ic }}"></i>
                    </div>
                    <div class="value">{{ $val }}</div>
                    <div class="label">{{ $lbl }}</div>
                </div>
            </div>
            @endforeach
        </div>
        <h6 class="fw-700 mb-2">Sessions Overview</h6>
        <div class="table-responsive">
            <table class="table table-bordered align-middle">
                <thead class="table-light"><tr><th>Title</th><th>Trainer</th><th>Status</th><th>Enrolled</th></tr></thead>
                <tbody>
                @foreach($data['sessions'] as $s)
                    <tr>
                        <td>{{ $s->title }}</td>
                        <td>{{ $s->trainer->name ?? '—' }}</td>
                        <td><span class="badge {{ $s->status_badge }}">{{ ucfirst($s->status) }}</span></td>
                        <td>{{ $s->enrollments_count }}</td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>

    @elseif($report->type === 'users')
        @foreach(['admins'=>'Admins','trainers'=>'Trainers','trainees'=>'Trainees'] as $key=>$label)
        <h6 class="fw-700 mb-2 mt-3">{{ $label }} ({{ $data[$key]->count() }})</h6>
        <div class="table-responsive mb-3">
            <table class="table table-bordered table-sm align-middle">
                <thead class="table-light"><tr><th>Name</th><th>Email</th><th>Phone</th><th>Status</th><th>Joined</th></tr></thead>
                <tbody>
                @foreach($data[$key] as $u)
                    <tr>
                        <td>{{ $u->name }}</td><td>{{ $u->email }}</td>
                        <td>{{ $u->phone ?? '—' }}</td>
                        <td>{{ $u->is_active ? 'Active' : 'Inactive' }}</td>
                        <td>{{ $u->created_at->format('d M Y') }}</td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
        @endforeach

    @elseif($report->type === 'sessions')
        <div class="table-responsive">
            <table class="table table-bordered align-middle">
                <thead class="table-light"><tr><th>Title</th><th>Trainer</th><th>Start</th><th>End</th><th>Status</th><th>Location</th></tr></thead>
                <tbody>
                @foreach($data['sessions'] as $s)
                    <tr>
                        <td>{{ $s->title }}</td><td>{{ $s->trainer->name ?? '—' }}</td>
                        <td>{{ $s->start_date->format('d M Y') }}</td>
                        <td>{{ $s->end_date->format('d M Y') }}</td>
                        <td>{{ ucfirst($s->status) }}</td>
                        <td>{{ $s->location ?? '—' }}</td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>

    @elseif($report->type === 'enrollments')
        <div class="table-responsive">
            <table class="table table-bordered align-middle">
                <thead class="table-light"><tr><th>Trainee</th><th>Session</th><th>Status</th><th>Enrolled At</th></tr></thead>
                <tbody>
                @foreach($data['enrollments'] as $e)
                    <tr>
                        <td>{{ $e->trainee->name ?? '—' }}</td>
                        <td>{{ $e->session->title ?? '—' }}</td>
                        <td>{{ ucfirst($e->status) }}</td>
                        <td>{{ $e->created_at->format('d M Y') }}</td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>

    @elseif($report->type === 'materials')
        <div class="table-responsive">
            <table class="table table-bordered align-middle">
                <thead class="table-light"><tr><th>Title</th><th>Session</th><th>Uploaded By</th><th>Type</th><th>Size</th><th>Date</th></tr></thead>
                <tbody>
                @foreach($data['materials'] as $m)
                    <tr>
                        <td>{{ $m->title }}</td>
                        <td>{{ $m->session->title ?? '—' }}</td>
                        <td>{{ $m->uploader->name ?? '—' }}</td>
                        <td>{{ ucfirst($m->material_type) }}</td>
                        <td>{{ $m->file_size_human }}</td>
                        <td>{{ $m->created_at->format('d M Y') }}</td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    @endif
</div>
@endsection
