<?php $__env->startSection('title','Reports'); ?>
<?php $__env->startSection('page-title','Reports'); ?>

<?php $__env->startSection('content'); ?>
<div class="row g-3">
    
    <div class="col-lg-4">
        <div class="form-card h-100">
            <h6 class="fw-700 mb-3"><i class="fa-solid fa-chart-bar me-2 text-primary"></i>Generate Report</h6>
            <form action="<?php echo e(route('admin.reports.generate')); ?>" method="POST">
                <?php echo csrf_field(); ?>
                <div class="mb-3">
                    <label class="form-label fw-600 small">Report Title *</label>
                    <input type="text" name="title" class="form-control" placeholder="e.g. April Users Report" required>
                </div>
                <div class="mb-4">
                    <label class="form-label fw-600 small">Report Type *</label>
                    <select name="type" class="form-select" required>
                        <option value="">Select type…</option>
                        <option value="summary">Summary (All Data)</option>
                        <option value="users">Users Report</option>
                        <option value="sessions">Sessions Report</option>
                        <option value="enrollments">Enrollments Report</option>
                        <option value="materials">Materials Report</option>
                    </select>
                </div>
                <button type="submit" class="btn btn-primary text-white w-100">
                    <i class="fa-solid fa-file-chart-column me-2"></i>Generate
                </button>
            </form>
        </div>
    </div>

    
    <div class="col-lg-8">
        <div class="table-card">
            <div class="table-header"><strong>Generated Reports</strong></div>
            <div class="table-responsive">
                <table class="table table-hover align-middle mb-0">
                    <thead><tr><th>Title</th><th>Type</th><th>Generated By</th><th>Date</th><th>Actions</th></tr></thead>
                    <tbody>
                    <?php $__empty_1 = true; $__currentLoopData = $reports; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $r): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?>
                        <tr>
                            <td class="fw-500"><?php echo e($r->title); ?></td>
                            <td><span class="badge badge-info"><?php echo e(ucfirst($r->type)); ?></span></td>
                            <td class="small"><?php echo e($r->generator->name ?? '—'); ?></td>
                            <td class="small text-muted"><?php echo e($r->created_at->format('d M Y H:i')); ?></td>
                            <td>
                                <div class="d-flex gap-1">
                                    <a href="<?php echo e(route('admin.reports.show',$r)); ?>" class="btn btn-sm btn-outline-info" title="View">
                                        <i class="fa-solid fa-eye"></i>
                                    </a>
                                    <form action="<?php echo e(route('admin.reports.destroy',$r)); ?>" method="POST"
                                        onsubmit="return confirm('Delete this report?')">
                                        <?php echo csrf_field(); ?> <?php echo method_field('DELETE'); ?>
                                        <button class="btn btn-sm btn-outline-danger" title="Delete">
                                            <i class="fa-solid fa-trash"></i>
                                        </button>
                                    </form>
                                </div>
                            </td>
                        </tr>
                    <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?>
                        <tr><td colspan="5" class="text-center text-muted py-5">No reports generated yet.</td></tr>
                    <?php endif; ?>
                    </tbody>
                </table>
            </div>
            <?php if($reports->hasPages()): ?>
                <div class="p-3"><?php echo e($reports->links()); ?></div>
            <?php endif; ?>
        </div>
    </div>
</div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.app', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?><?php /**PATH C:\xampp\htdocs\tms\resources\views/admin/reports/index.blade.php ENDPATH**/ ?>