<?php $__env->startSection('title', $report->title); ?>
<?php $__env->startSection('page-title', 'Report: ' . $report->title); ?>

<?php $__env->startSection('content'); ?>
<div class="form-card">
    <div class="d-flex justify-content-between align-items-center mb-4 flex-wrap gap-2">
        <div>
            <h5 class="fw-700 mb-1"><?php echo e($report->title); ?></h5>
            <span class="badge badge-info me-2"><?php echo e(ucfirst($report->type)); ?></span>
            <span class="text-muted small">Generated by <?php echo e($report->generator->name ?? '—'); ?> on <?php echo e($report->created_at->format('d M Y H:i')); ?></span>
        </div>
        <div class="d-flex gap-2">
            <button onclick="window.print()" class="btn btn-sm btn-outline-secondary">
                <i class="fa-solid fa-print me-1"></i>Print
            </button>
            <form action="<?php echo e(route('admin.reports.destroy',$report)); ?>" method="POST"
                onsubmit="return confirm('Delete this report permanently?')">
                <?php echo csrf_field(); ?> <?php echo method_field('DELETE'); ?>
                <button class="btn btn-sm btn-outline-danger"><i class="fa-solid fa-trash me-1"></i>Delete</button>
            </form>
            <a href="<?php echo e(route('admin.reports.index')); ?>" class="btn btn-sm btn-outline-secondary">Back</a>
        </div>
    </div>

    <?php if($report->type === 'summary'): ?>
        <div class="row g-3 mb-4">
            <?php $__currentLoopData = [
                ['Total Users',     $data['total_users'],     '#dbeafe','#2563eb','fa-users'],
                ['Trainers',        $data['total_trainers'],  '#dcfce7','#16a34a','fa-chalkboard-user'],
                ['Trainees',        $data['total_trainees'],  '#fef9c3','#ca8a04','fa-user-graduate'],
                ['Total Sessions',  $data['total_sessions'],  '#f3e8ff','#9333ea','fa-calendar-days'],
                ['Active Sessions', $data['active_sessions'], '#dcfce7','#16a34a','fa-circle-play'],
                ['Enrollments',     $data['total_enrolls'],   '#ffedd5','#ea580c','fa-clipboard-list'],
                ['Materials',       $data['total_materials'], '#e0f2fe','#0284c7','fa-file-arrow-up'],
            ]; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as [$lbl,$val,$bg,$ic,$icon]): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
            <div class="col-6 col-md-3">
                <div class="stat-card text-center">
                    <div class="icon mx-auto" style="background:<?php echo e($bg); ?>">
                        <i class="fa-solid <?php echo e($icon); ?>" style="color:<?php echo e($ic); ?>"></i>
                    </div>
                    <div class="value"><?php echo e($val); ?></div>
                    <div class="label"><?php echo e($lbl); ?></div>
                </div>
            </div>
            <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
        </div>
        <h6 class="fw-700 mb-2">Sessions Overview</h6>
        <div class="table-responsive">
            <table class="table table-bordered align-middle">
                <thead class="table-light"><tr><th>Title</th><th>Trainer</th><th>Status</th><th>Enrolled</th></tr></thead>
                <tbody>
                <?php $__currentLoopData = $data['sessions']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $s): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
                    <tr>
                        <td><?php echo e($s->title); ?></td>
                        <td><?php echo e($s->trainer->name ?? '—'); ?></td>
                        <td><span class="badge <?php echo e($s->status_badge); ?>"><?php echo e(ucfirst($s->status)); ?></span></td>
                        <td><?php echo e($s->enrollments_count); ?></td>
                    </tr>
                <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
                </tbody>
            </table>
        </div>

    <?php elseif($report->type === 'users'): ?>
        <?php $__currentLoopData = ['admins'=>'Admins','trainers'=>'Trainers','trainees'=>'Trainees']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $key=>$label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
        <h6 class="fw-700 mb-2 mt-3"><?php echo e($label); ?> (<?php echo e($data[$key]->count()); ?>)</h6>
        <div class="table-responsive mb-3">
            <table class="table table-bordered table-sm align-middle">
                <thead class="table-light"><tr><th>Name</th><th>Email</th><th>Phone</th><th>Status</th><th>Joined</th></tr></thead>
                <tbody>
                <?php $__currentLoopData = $data[$key]; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $u): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
                    <tr>
                        <td><?php echo e($u->name); ?></td><td><?php echo e($u->email); ?></td>
                        <td><?php echo e($u->phone ?? '—'); ?></td>
                        <td><?php echo e($u->is_active ? 'Active' : 'Inactive'); ?></td>
                        <td><?php echo e($u->created_at->format('d M Y')); ?></td>
                    </tr>
                <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
                </tbody>
            </table>
        </div>
        <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>

    <?php elseif($report->type === 'sessions'): ?>
        <div class="table-responsive">
            <table class="table table-bordered align-middle">
                <thead class="table-light"><tr><th>Title</th><th>Trainer</th><th>Start</th><th>End</th><th>Status</th><th>Location</th></tr></thead>
                <tbody>
                <?php $__currentLoopData = $data['sessions']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $s): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
                    <tr>
                        <td><?php echo e($s->title); ?></td><td><?php echo e($s->trainer->name ?? '—'); ?></td>
                        <td><?php echo e($s->start_date->format('d M Y')); ?></td>
                        <td><?php echo e($s->end_date->format('d M Y')); ?></td>
                        <td><?php echo e(ucfirst($s->status)); ?></td>
                        <td><?php echo e($s->location ?? '—'); ?></td>
                    </tr>
                <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
                </tbody>
            </table>
        </div>

    <?php elseif($report->type === 'enrollments'): ?>
        <div class="table-responsive">
            <table class="table table-bordered align-middle">
                <thead class="table-light"><tr><th>Trainee</th><th>Session</th><th>Status</th><th>Enrolled At</th></tr></thead>
                <tbody>
                <?php $__currentLoopData = $data['enrollments']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $e): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
                    <tr>
                        <td><?php echo e($e->trainee->name ?? '—'); ?></td>
                        <td><?php echo e($e->session->title ?? '—'); ?></td>
                        <td><?php echo e(ucfirst($e->status)); ?></td>
                        <td><?php echo e($e->created_at->format('d M Y')); ?></td>
                    </tr>
                <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
                </tbody>
            </table>
        </div>

    <?php elseif($report->type === 'materials'): ?>
        <div class="table-responsive">
            <table class="table table-bordered align-middle">
                <thead class="table-light"><tr><th>Title</th><th>Session</th><th>Uploaded By</th><th>Type</th><th>Size</th><th>Date</th></tr></thead>
                <tbody>
                <?php $__currentLoopData = $data['materials']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $m): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
                    <tr>
                        <td><?php echo e($m->title); ?></td>
                        <td><?php echo e($m->session->title ?? '—'); ?></td>
                        <td><?php echo e($m->uploader->name ?? '—'); ?></td>
                        <td><?php echo e(ucfirst($m->material_type)); ?></td>
                        <td><?php echo e($m->file_size_human); ?></td>
                        <td><?php echo e($m->created_at->format('d M Y')); ?></td>
                    </tr>
                <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
                </tbody>
            </table>
        </div>
    <?php endif; ?>
</div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.app', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?><?php /**PATH C:\xampp\htdocs\tms\resources\views\admin\reports\show.blade.php ENDPATH**/ ?>